### PR TITLE
Fixed image Urls

### LINKED ISSUE #877: Fixing broken images on Armada website
[](url)

### PR DESCRIPTION
**Pull request by dans77777**
fixes #877 
Screenshot (56)
7

### CODE REVIEW

**Comment by stackedsax** [comment]
@dans77777 Looks great, however, I think you may have done too much work :)

It looks like you're checking in a whole bunch of generated code that Jekyll produced.  I think you just need to check in the one image to the main branch and then let the 'Deploy GH-pages' action (https://github.com/G-Research/armada/actions/workflows/main.yml) do the rest.

We have it set up like this:
1. merge doc changes into the main branch
2. The Deploy GH-pages action runs and copies updated files from the main branch to the gh-pages branch
3. new files in gh-pages are automatically recompiled by Github and deployed to the github pages site

The only step you need to take is to merge the updated image (and maybe a css or an .md doc that references that image) into the main branch.  The rest should be handled for you.  Instead of 239 files updated (!) you will have about 1-2. 

Maybe connect with @jgiannuzzi and @pavlovic-ivan to make sure I'm telling you the right info.

**Comment by dans77777** [comment]
> @dans77777 Looks great, however, I think you may have done too much work :)
> 
> It looks like you're checking in a whole bunch of generated code that Jekyll produced. I think you just need to check in the one image to the main branch and then let the 'Deploy GH-pages' action (https://github.com/G-Research/armada/actions/workflows/main.yml) do the rest.
> 
> We have it set up like this:
> 
> 1. merge doc changes into the main branch
> 2. The Deploy GH-pages action runs and copies updated files from the main branch to the gh-pages branch
> 3. new files in gh-pages are automatically recompiled by Github and deployed to the github pages site
> 
> The only step you need to take is to merge the updated image (and maybe a css or an .md doc that references that image) into the main branch. The rest should be handled for you. Instead of 239 files updated (!) you will have about 1-2.
> 
> Maybe connect with @jgiannuzzi and @pavlovic-ivan to make sure I'm telling you the right info.

@stackedsax Thanks for this. is that mean I just need to work on master branch and not on gh-pages branch?

**Comment by dans77777** [comment]
@stackedsax Should I merge this branch to G-reserch/gh-pages? How can just merge only one file instead of 239 files that were changed by me

**Comment by ljubon** [comment]
hi @dans77777 , feel free to ping me on Slack where we can jump on a call and go though PR
ideal PR would be only change we need to introduce on top of current code
I can help you with Git and make this PR a bit cleaner, and you can help me understand what was originally a fix here... or we can start with what was originally a problem here :)

**Pull request closed without merging**
