### PR TITLE
add logo folder inside docs folder

### PR DESCRIPTION
**Pull request by Debiday**
Added the logo folder inside docs folder to keep main folder clean.

### CODE REVIEW

**Comment by Debiday** [comment]
Hi @mariannovotny I've added the armada logos into the folder, can I trouble you to check if it's appropriate? Thank you😊

**Comment by Debiday** [comment]
Hi @stackedsax, I've redone the PR from the [previous PR #833](https://github.com/G-Research/armada/pull/833). I wonder if this works better now?

**Review by robertdavidsmith — APPROVED** [review]

**Comment by Debiday** [comment]
Thank you @jimbobby5! 😊

**Comment by Debiday** [comment]
Thank you @robertdavidsmith! 😊

**Comment by Debiday** [comment]
Thank you @c-rindi!

**Pull request merged**
