### PR TITLE
adding coverage to go

### LINKED ISSUE #1838: Add Code Coverage to our go code
Code coverage provides a nice way to view how much of your code is tested.  I don't suggest trying to fail the build but it would be nice to get information about your test coverage on PRs.  

You can see an example here: https://github.com/apache/yunikorn-k8shim/pull/488#issuecomment-1323041260

You can get it for go by adding this to github action:

```
      - name: Code coverage
        uses: codecov/codecov-action@v3
```
And making sure the codecov picks up the converge file from go test.

### PR DESCRIPTION
**Pull request by kannon92**
Fixes #1838 

Add a github action that uploads code coverage for our unit/integration tests.

### CODE REVIEW

**Comment by ClifHouck** [comment]
WDYT about adding a summary of the report to the action or PR? Something like https://josh-ops.com/posts/github-code-coverage/

**Comment by kannon92** [comment]
> WDYT about adding a summary of the report to the action or PR? Something like https://josh-ops.com/posts/github-code-coverage/

If this is working, I think I should get something like this in the PR?

https://github.com/apache/yunikorn-k8shim/pull/472#issuecomment-1302156365

**Comment by ClifHouck** [comment]
> > WDYT about adding a summary of the report to the action or PR? Something like https://josh-ops.com/posts/github-code-coverage/
> 
> If this is working, I think I should get something like this in the PR?
> 
> [apache/yunikorn-k8shim#472 (comment)](https://github.com/apache/yunikorn-k8shim/pull/472#issuecomment-1302156365)

Oh, interesting. I'm not familiar with codecov. It looks like the coverage action ran in your PR though, and I didn't see a summary anywhere. So I guess not quite working?

**Review by ClifHouck — APPROVED** [review]
LGTM

**Pull request merged**
