### PR TITLE
Fixes to quickstart docs

### PR DESCRIPTION
**Pull request by dejanzele**
CHANGELOG
* Pinpoint k8s version to v1.21.10 in kind config
* Add scripts for provisioning and destroying a local Armada cluster
* Improve quickstart doc

### CODE REVIEW

**Comment by kannon92** [comment]
I just started today so I'm testing out these scripts now!

**Comment by severinson** [comment]
Did you have a look at the tests-e2e-setup makefile target? It also spins up a test environment for Armada.
It looks like at least Pulsar is missing from the setup script. We're in the middle of some architecture changes.
I'd be happy to have a meeting to discuss these. Are you on Slack?

**Comment by severinson** [comment]
Should we update this to include Pulsar?

**Review by severinson — APPROVED** [review]

**Comment by kannon92** [comment]
I tested this out on my mac m1.  The helm chart for pulsar doesn't seem to work with M1.  I don't think this should block because it looks like pulsar has issues on M1 anyway.

```
Kevins-MBP:armada-dejanzele kevinhannon$ helm install pulsar apache/pulsar --wait
W0601 16:26:43.360740   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.362699   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.364469   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.369654   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.556365   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.561467   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.561478   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0601 16:26:43.561477   89577 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: INSTALLATION FAILED: timed out waiting for the condition

```

**Review by richscott — APPROVED** [review]

**Review by jimbobby5 — APPROVED** [review]

**Pull request merged**
