### PR TITLE
enable codeql analysis for scanning code

### PR DESCRIPTION
**Pull request by ljubon**
https://github.com/github/codeql-action#codeql-action

### CODE REVIEW

**Comment by jankaspar** [comment]
Hi @ljubon, I am not sure why circleci is not running the build for your fork, have you changed some setting to prevent that, please? The merging currently requires these checks to pass.

**Review by jankaspar — APPROVED** [review]

**Comment by ljubon** [comment]
> Hi @ljubon, I am not sure why circleci is not running the build for your fork, have you changed some setting to prevent that, please? The merging currently requires these checks to pass.

Hi @jankaspar, thanks for approving my changes!
I couldn't tell at the moment what seems to be a problem, do you see maybe button re-run/run checks or build 🤔 ? 
On some repo, only maintainers can run checks, in my case I don't have permissions for that action

**Comment by jgiannuzzi** [comment]
I am under the impression that CircleCI does not run on pull requests. It seems to only run on pushes to a branch from the same repo.

One thing you could try @ljubon: sign up for CircleCI and link your fork so that it runs the checks on your branch - maybe that will unblock the situation?

**Comment by ljubon** [comment]
dear @jankaspar  , sorry for waiting for these changes...
unfortunately, I found that CircleCI blocked my runs as I hit their radar somehow 😕 [violation](https://support.circleci.com/hc/en-us/articles/360043679453-CircleCI-Terms-of-Service-Violation-Sanctioned-Country)
_FYI_ I made an appeal and currently I'm waiting for a response. I'll get back to you as soon as they unblock my runs 🙏

**Comment by ljubon** [comment]
> dear @jankaspar , sorry for waiting for these changes...
> unfortunately, I found that CircleCI blocked my runs as I hit their radar somehow 😕 [violation](https://support.circleci.com/hc/en-us/articles/360043679453-CircleCI-Terms-of-Service-Violation-Sanctioned-Country)
> _FYI_ I made an appeal and currently I'm waiting for a response. I'll get back to you as soon as they unblock my runs 🙏

CircleCI runs are enabled again for my account, all checks are passed 💯  @jankaspar @jgiannuzzi

**Comment by jgiannuzzi** [comment]
Once we migrate to GitHub Actions (see #597), this will be a thing of the past 😄

**Pull request merged**
